/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.github.thorqin.webapi.smc;

import java.awt.Dialog;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import com.github.thorqin.webapi.security.SecuritySetting.URLMatcher;
import com.github.thorqin.webapi.security.SecuritySetting.URLMatcher.RedirectionInfo;
import com.github.thorqin.webapi.utility.Serializer;
import com.github.thorqin.webapi.utility.StringUtil;

/**
 *
 * @author nuo.qin
 */
public class MatcherDialog extends javax.swing.JDialog {
	
	class SessionVariableModel extends MapTableModelBase<Set<String>> {
		private final Map<String, Set<String>> items;
		public SessionVariableModel(Map<String, Set<String>> items) {
			super(items, new String[]{"Session Variable", "Value Should Contained"});
			this.items = items;
		}
		public Map<String, Set<String>> getItems() {
			return this.items;
		}
		@Override
		protected String getColValue(int columnIndex, Map.Entry<String, Set<String>> entry) {
			switch (columnIndex) {
				case 0:
					return entry.getKey();
				case 1:
					return StringUtil.join(entry.getValue());
				default:
					return null;
			}
		}

	}
	class RedirectionModel extends MapTableModelBase<RedirectionInfo> {
		private final Map<String, RedirectionInfo> items;
		public RedirectionModel(Map<String, RedirectionInfo> items) {
			super(items, new String[]{"Redirection URL", "Roles", "Users"});
			this.items = items;
		}
		public Map<String, RedirectionInfo> getItems() {
			return this.items;
		}
		@Override
		protected Object getColValue(int columnIndex, Map.Entry<String, RedirectionInfo> entry) {
			switch (columnIndex) {
				case 0:
					return entry.getKey();
				case 1:
					return entry.getValue().roles;
				case 2:
					return entry.getValue().users;
				default:
					return null;
			}
		}

	}
	
	private URLMatcher matcher;
	private List<URLMatcher> matcherList;
	private boolean ok = false;
	private SessionVariableModel sessionModel = null;
	private RedirectionModel redirectionModel = null;

	public MatcherDialog(Dialog parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	public URLMatcher getMatcher() {
		return matcher;
	}
	
	public void setMatcher(URLMatcher matcher) {
		this.matcher = matcher;
	}
	
	public void setMatcherList(List<URLMatcher> matcherList) {
		this.matcherList = matcherList;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelSwitch = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textURL = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textProtocol = new javax.swing.JTextField();
        textMethod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        textDomain = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textPort = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textMatcherName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDescription = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonAddSessionVariable = new javax.swing.JButton();
        buttonDeleteSessionVariable = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableSessionVariable = new javax.swing.JTable();
        panelMapping = new javax.swing.JPanel();
        textScenario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textOperation = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textResourceType = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textResourceID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        buttonAddMatcher = new javax.swing.JButton();
        buttonDeleteMatcher = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRedirections = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        buttonCancel = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("URL Matcher");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("<html>URL Path <span style=\"color:blue\">(Without scheme, domain, port and server context path)</span></html>");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel25.setToolTipText("<html>To avoid hard-code define resource type, resource id and operation<br>\nfrom the 'Mapping' tab, you can use {res}, {resid} and {operation} keywords<br>\nto dynamically extract those information from the request URL. <br>\nKeyword '*' means to '[^?/&=]+' , keyword '+' means to '.+', <br>\nkeyword '?+' means to '(\\?.*)?' </html>");

        jLabel1.setText("Scheme (http, https etc...)");

        jLabel7.setText("Method (get, post, delete etc...)");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel26.setToolTipText("<html>Can not specify multiple protocals. <br>If keep empty that will match all protocals.</html>");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel27.setToolTipText("<html>Can specify multiple http methods, use ',' to split items. <br>\nIf keep empty that will match all methods.</html>");

        jLabel2.setText("Domain (domain name, IP address)");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel28.setToolTipText("<html>Can specify multiple domains, use ',' to split items. <br>\nIf keep empty that will match all domains.</html>");

        jLabel9.setText("Port (Server listen port)");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel29.setToolTipText("<html>Can specify multiple http ports, use ',' to split items. <br>\nIf keep empty that will match all ports.</html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Matcher Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Description");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDescription)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addComponent(jLabel4)
                    .addComponent(textMatcherName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textURL)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textProtocol, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel26))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel28)))
                            .addComponent(textDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27))
                            .addComponent(textMethod)
                            .addComponent(textPort, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMatcherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel29))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        panelSwitch.addTab("Common & Request Matching", jPanel4);

        jPanel1.setOpaque(false);

        buttonAddSessionVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/add.png"))); // NOI18N
        buttonAddSessionVariable.setText("Add Session Variable");
        buttonAddSessionVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSessionVariableActionPerformed(evt);
            }
        });

        buttonDeleteSessionVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/delete.png"))); // NOI18N
        buttonDeleteSessionVariable.setText("Delete");
        buttonDeleteSessionVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteSessionVariableActionPerformed(evt);
            }
        });

        tableSessionVariable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Session Variable", "Value Should Contained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSessionVariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSessionVariableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableSessionVariable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAddSessionVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteSessionVariable))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddSessionVariable)
                    .addComponent(buttonDeleteSessionVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSwitch.addTab("Session Matching", jPanel1);

        panelMapping.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel22.setToolTipText("<html>Mapping to specified operation <br>(Can not contain multiple values)</html>");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel24.setToolTipText("<html>Mapping to specified scenario <br>(Can not contain multiple values)</html>");

        jLabel17.setText("Operation");

        jLabel19.setText("Scenario");

        jLabel11.setText("Resource Type");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel21.setToolTipText("<html>Mapping to specified resource type <br>(Can not contain multiple values)</html>");

        jLabel15.setText("Resource ID");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/tooltip.png"))); // NOI18N
        jLabel23.setToolTipText("<html>Mapping to specified resource id <br>(Can not contain multiple values)</html>");

        javax.swing.GroupLayout panelMappingLayout = new javax.swing.GroupLayout(panelMapping);
        panelMapping.setLayout(panelMappingLayout);
        panelMappingLayout.setHorizontalGroup(
            panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMappingLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textResourceID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textResourceType)
                    .addGroup(panelMappingLayout.createSequentialGroup()
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMappingLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(panelMappingLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(textScenario)
                    .addGroup(panelMappingLayout.createSequentialGroup()
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMappingLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(panelMappingLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        panelMappingLayout.setVerticalGroup(
            panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMappingLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMappingLayout.createSequentialGroup()
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textScenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMappingLayout.createSequentialGroup()
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textResourceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textResourceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        panelSwitch.addTab("Mapping To", panelMapping);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        buttonAddMatcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/add.png"))); // NOI18N
        buttonAddMatcher.setText("Add Redirection Policy");
        buttonAddMatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMatcherActionPerformed(evt);
            }
        });

        buttonDeleteMatcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/github/thorqin/webapi/smc/delete.png"))); // NOI18N
        buttonDeleteMatcher.setText("Delete");
        buttonDeleteMatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteMatcherActionPerformed(evt);
            }
        });

        tableRedirections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Redirection URL", "Roles", "Users"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableRedirections.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRedirectionsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableRedirections);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonAddMatcher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteMatcher)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddMatcher)
                    .addComponent(buttonDeleteMatcher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSwitch.addTab("Redirections", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	public boolean isOk() {
		return ok;
	}
	
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		ok = false;
		
		if (matcher == null)
		   matcher = new URLMatcher();
		textMatcherName.setText(matcher.name);
		textDescription.setText(matcher.description);
		textURL.setText(StringUtil.join(matcher.url));
		textProtocol.setText(StringUtil.join(matcher.scheme));
		textDomain.setText(StringUtil.join(matcher.domain));
		textMethod.setText(StringUtil.join(matcher.method));
		textPort.setText(StringUtil.join(matcher.port));
		
		textResourceType.setText(matcher.resType);
		textResourceID.setText(matcher.resId);
		textOperation.setText(matcher.operation);
		textScenario.setText(matcher.scenario);
		sessionModel = new SessionVariableModel(Serializer.copy(matcher.sessionVariables));
		redirectionModel = new RedirectionModel(Serializer.copy(matcher.redirection));
		tableSessionVariable.setModel(sessionModel);
		tableRedirections.setModel(redirectionModel);
		textMatcherName.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        if (textMatcherName.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, 
					"Must specify name!", 
					"Error", JOptionPane.WARNING_MESSAGE);
			panelSwitch.setSelectedIndex(0);
			textMatcherName.requestFocus(true);
			return;
		}
		if (textDescription.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, 
					"Must specify description!", 
					"Error", JOptionPane.WARNING_MESSAGE);
			panelSwitch.setSelectedIndex(0);
			textDescription.requestFocus(true);
			return;
		}
		if (textURL.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(null, 
					"Must provide URL rule!", 
					"Error", JOptionPane.WARNING_MESSAGE);
			panelSwitch.setSelectedIndex(0);
			textURL.requestFocus(true);
			return;
		}

		String name = textMatcherName.getText().trim();
		for (URLMatcher m : matcherList) {
			if (!m.equals(matcher) && m.name.equals(name)) {
				JOptionPane.showMessageDialog(null, 
					"Must specify unique matcher name!", 
					"Error", JOptionPane.WARNING_MESSAGE);
				panelSwitch.setSelectedIndex(0);
				textMatcherName.requestFocus(true);
				return;
			}
		}
		matcher.name = name;
		matcher.description = textDescription.getText();
		matcher.url = StringUtil.toStringSet(textURL.getText());
		matcher.scheme = StringUtil.toStringSet(textProtocol.getText().toLowerCase());
		matcher.domain = StringUtil.toStringSet(textDomain.getText().toLowerCase());
		matcher.method = StringUtil.toStringSet(textMethod.getText().toLowerCase());
		matcher.port = StringUtil.toStringSet(textPort.getText());
		
		matcher.resType = textResourceType.getText().trim();
		matcher.resId = textResourceID.getText();
		matcher.operation = textOperation.getText();
		matcher.scenario = textScenario.getText();
		matcher.sessionVariables = sessionModel.getItems();
		matcher.redirection = redirectionModel.getItems();
		ok = true;
		this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonAddMatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMatcherActionPerformed
		RedirectionDialog dialog = new RedirectionDialog(this, true);
		dialog.keySet = matcher.redirection.keySet();
		dialog.setVisible(true);
        if (dialog.isOK) {
			redirectionModel.getItems().put(dialog.url, dialog.info);
            redirectionModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_buttonAddMatcherActionPerformed

    private void buttonDeleteMatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteMatcherActionPerformed
		List<String> removed = new LinkedList<>();
        for (int rownum : tableRedirections.getSelectedRows()) {
			removed.add(redirectionModel.get(rownum).getKey());
        }
		for (String k: removed)
			redirectionModel.getItems().remove(k);
        redirectionModel.fireTableDataChanged();
    }//GEN-LAST:event_buttonDeleteMatcherActionPerformed

    private void tableRedirectionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRedirectionsMouseClicked
        int rowId = tableRedirections.getSelectedRow();
        if (evt.getClickCount() == 2) {
			String k = redirectionModel.get(rowId).getKey();
			RedirectionInfo value = redirectionModel.getItems().get(k);			
            RedirectionDialog dialog = new RedirectionDialog(this, true);
			dialog.url = k;
			dialog.info = Serializer.copy(value);
			dialog.keySet = redirectionModel.getItems().keySet();
			dialog.setVisible(true);
            if (dialog.isOK) {
				redirectionModel.getItems().remove(k);
				redirectionModel.getItems().put(dialog.url, dialog.info);
                redirectionModel.fireTableDataChanged();
                tableRedirections.setRowSelectionInterval(rowId, rowId);
            }
        }
    }//GEN-LAST:event_tableRedirectionsMouseClicked

    private void buttonAddSessionVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSessionVariableActionPerformed
        KeyValueDialog dialog = new KeyValueDialog(this, true);
		dialog.nameSet = sessionModel.getItems().keySet();
		dialog.setVisible(true);
        if (dialog.isOK()) {
			sessionModel.getItems().put(dialog.name, StringUtil.toStringSet(dialog.value, ","));
            sessionModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_buttonAddSessionVariableActionPerformed

    private void buttonDeleteSessionVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteSessionVariableActionPerformed
        List<String> removed = new LinkedList<>();
        for (int rownum : tableSessionVariable.getSelectedRows()) {
			removed.add(sessionModel.get(rownum).getKey());
        }
		for (String k: removed)
			sessionModel.getItems().remove(k);
        sessionModel.fireTableDataChanged();
    }//GEN-LAST:event_buttonDeleteSessionVariableActionPerformed

    private void tableSessionVariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSessionVariableMouseClicked
        int rowId = tableSessionVariable.getSelectedRow();
        if (evt.getClickCount() == 2) {
			String k = sessionModel.get(rowId).getKey();
			String value = StringUtil.join(sessionModel.getItems().get(k));			
            KeyValueDialog dialog = new KeyValueDialog(this, true);
            dialog.doEdit(k, value, sessionModel.getItems().keySet());
            if (dialog.isOK()) {
				sessionModel.getItems().put(dialog.name, StringUtil.toStringSet(dialog.value, ","));
                sessionModel.fireTableDataChanged();
                tableSessionVariable.setRowSelectionInterval(rowId, rowId);
            }
        }
    }//GEN-LAST:event_tableSessionVariableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddMatcher;
    private javax.swing.JButton buttonAddSessionVariable;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDeleteMatcher;
    private javax.swing.JButton buttonDeleteSessionVariable;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelMapping;
    private javax.swing.JTabbedPane panelSwitch;
    private javax.swing.JTable tableRedirections;
    private javax.swing.JTable tableSessionVariable;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textDomain;
    private javax.swing.JTextField textMatcherName;
    private javax.swing.JTextField textMethod;
    private javax.swing.JTextField textOperation;
    private javax.swing.JTextField textPort;
    private javax.swing.JTextField textProtocol;
    private javax.swing.JTextField textResourceID;
    private javax.swing.JTextField textResourceType;
    private javax.swing.JTextField textScenario;
    private javax.swing.JTextField textURL;
    // End of variables declaration//GEN-END:variables
}
